name: Hello Worl Workflow

on:
  push:
    branches: [ main ]

jobs:
  hello-job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Hello World
        run: echo "Hello World!"
      - name: Setup npm auth
        run: npm config set @YOUR_ORG:registry https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish npm package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}